### ISSUE TITLE
Hide exported items

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#12]
It would be good to be able to hide exported items from the list of activities. In fact, this should probably be the default view.

**Comment by chri55w** [comment]
Approaching this by adding a CheckBox with the other Time Log search criteria to 'Show Exported Logs' by default this will be unchecked however a 'Show Exported Logs By Default' could additionally be added to the settings flyout

**Comment by chri55w** [comment]
As shown in the images below the Show Exported Logs Checkbox updated the Time Log grid, showing and hiding the already exported time logs as expected
![image](https://cloud.githubusercontent.com/assets/10941226/14003712/9496e2cc-f14c-11e5-885a-07ea80aa78b0.png)
![image](https://cloud.githubusercontent.com/assets/10941226/14003714/9d5ea2d2-f14c-11e5-8493-3b058391e97e.png)
