### ISSUE TITLE
Live Database System

### ISSUE THREAD

**Issue by chri55w** [chri55w/QuickBooks-Timer#26]
In order to maintain data integrity and sync all employee time log data to one location the application should use an online database where possible to store all data, the Import functionality should be removed to an external application which will not be needed by most users. a Local database will be used for offline interaction, this will fetch all the customer, service item, class, employee and TimerType data when connected to the live database and only temporarily store Time Logs when the user cannot connect to the Live Database

![image](https://cloud.githubusercontent.com/assets/10941226/14108758/9b031b8a-f5b6-11e5-8d3c-9a27ba49aa84.png)

**Comment by BradConnor** [comment]
Looks OK!

**Comment by chri55w** [comment]
Database has been created, Import application has been completed, Documentation to be provided within the WIKI.

Making changes to the Timer application to access Live Database before creating the Local Database and working with syncing functionality

**Comment by chri55w** [comment]
Database connections working, Importing data functions completed. Old import code removed and start-up process stripped to basics fetching all live data from database.

Created this UML Activity Diagram to help visualise the desired start up process
![image](https://cloud.githubusercontent.com/assets/10941226/14175129/e43310d6-f740-11e5-911b-34fa8cebe12c.png)

**Comment by chri55w** [comment]
Further Complications / Ideas have prompted me to look at some Data restructuring to avoid wasted space and improve maintainability. 

### Database Changes

![image](https://cloud.githubusercontent.com/assets/10941226/14211179/8ed2f4c8-f824-11e5-9589-180d49c360d4.png)

### Application Start Up Process Plan

![image](https://cloud.githubusercontent.com/assets/10941226/14211231/c971abec-f824-11e5-8c7e-ebc537b04842.png)

These changes are priority and will be implemented as soon as possible

**Comment by chri55w** [comment]
Given the size and complexity of these changes a lot of features have been disabled temporarily. That being said the remaining functionality has now been modified to work as designed with the Live and Local Database.

This issue will now be closed and replaced with several new issues to better log the Disabled features that must be re-enabled.
