### ISSUE TITLE
Word wrap on timer detail text box

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#27]
At present when you reach the end of the first line of the comments box, the text starts scrolling off to the right - with no horizontal scrollbar appearing - rather than wrap onto the next line. It would be better  to wrap, and to automatically create a vertical scrollbar when appropriate, as these comments can be quite long.

**Comment by chri55w** [comment]
This has been addressed in #19 but not released since, once the Live Database changes are completed and tested somewhat ill get an update to you.

**Comment by BradConnor** [comment]
Can I also enter newlines by pressing the Return key?

**Comment by chri55w** [comment]
This is actually disabled since I was unsure if it would be correctly imported into QuickBooks Pro since it somewhat breaks the Tab Delimited format of the export file. However if we can confirm this does not cause any issues I agree it would be a useful addition.

**Comment by BradConnor** [comment]
Hm, yes, that's a good question. Alex used to manage it in QBTimer, by using Ctrl-Return I think, and I remember having to painstakingly take the line breaks out of the comments each time I was generating the Excel reports from QuickBooks; but it's useful to be able to break up long comments.

**Comment by chri55w** [comment]
Yes, I also managed it myself in QBTimer, but having noticed the effect it had on the export I thought that it may have been causing more harm than good. 

Perhaps what we need is to be able to add new lines while in the Timer but when exporting replace all line breaks with a space character instead?

**Comment by BradConnor** [comment]
Yes, that would work
