### ISSUE TITLE
Change date on timer item

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#28]
When you create a timer item and then change the date to that of a previous day (say, for entering data retrospectively, like I just have for my visit to NHS-FV yesterday when I didn't have a PC with me), the item still stays in the 'today' view of the filtered list box. I have to change it to another time range to get it to refresh. Maybe trigger an auto refresh when detecting a date change?

**Comment by chri55w** [comment]
Yes, I seem to remember noticing this when I first implemented it but could not at the time figure out a way around it. Though one new idea:

Use a `DependencyProperty`on the `TimeLogEditorPanel`with a `PropertyChangedCallback`and trigger a command to Refresh the `TimeLog`panel when changed.

**Comment by chri55w** [comment]
Fixed this issue through the use of a property changed event handler on the TimeLog, defined in the MainViewModel (Timelog_PropertyChanged). Now whenever the Date property is updated the Time Log DataGrid is refreshed
