### ISSUE TITLE
Start and stop buttons in the task detail pane

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#31]
would be nice :-). Also maybe start on stop by right-clicking on the items in the grid list of active timers? Both nice-to-haves. I find myself getting confused as to what's active and what's not when I've got one timer type highlighted on the left and another highlighted in the grid list. Maybe I just need to get used to it.

**Comment by chri55w** [comment]
Do you mean the panel where you edit Time Logs? I'm sure I can add buttons there, and could add Start Stop Context menu items in the Time Log Grid too, Perhaps adding a form of highlighting to the time Log Data Grid would help show which Time Log is running?

**Comment by BradConnor** [comment]
Yes to all of those!

**Comment by chri55w** [comment]
Given the Changes to the Time Log Editor and future planned updates i dont think this is the ideal location for play / pause buttons. however adding 'Start' / 'Resume' and 'Pause' options in a right click menu would be useful. I will still look into a way in which we could highlight the currently running TimeLog in the dataGrid and i will try and find an additional location for Play / Pause interactions

**Comment by chri55w** [comment]
See Issue #47 and #48 for re-definition
