### ISSUE TITLE
Export button

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#32]
Should be able to specify the date up to which you export items. Or maybe even a date range. Or just those items selected in the grid list. For example, say I wanted to export up to the end of last month today... it'll also export the items I've already logged today as well, even though I still have more to log for today.

**Comment by BradConnor** [comment]
Ruddy users, never satisfied :-P

**Comment by chri55w** [comment]
If you look at the Second Column of the Time Log Data Grid
![image](https://cloud.githubusercontent.com/assets/10941226/14211437/00ab43ec-f826-11e5-965c-2a5e1aba73e2.png)
By un-checking the CheckBox here you wont export that log

**Comment by BradConnor** [comment]
Ah - I thought that was telling me what had and what hadn't been exported, not what I was going to export :-)

**Comment by chri55w** [comment]
Yeah I did wonder how clear it would be, if you hover over them it has `ToolTips`, the Icon on the displays if it has or has not been exported yet and the `CheckBox`is if you want it to export (By default it is the opposite of the Exported value)

Going to need to Write a User Manual for the application eventually I think haha
