### ISSUE TITLE
Create New Template - reset

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#55]
If I start creating a new template but then decide against it, those values that I put in there are still in there when I later maybe want to create one. We could either forget them as soon as that fly-in is closed with out creating a template, or have a reset button.

**Comment by chri55w** [comment]
Perhaps looking to add both of these options, I can have the items clear on the fly-out closing and also add a new button to reset the fields manually

**Comment by chri55w** [comment]
New Timer fields now reset when opening / closing the flyout and a new button has been added to reset the fields manually
![image](https://cloud.githubusercontent.com/assets/10941226/14717875/6348da30-07eb-11e6-91c7-8fbdeef67cf9.png)

Additionally a margin has been applied to the controls and the color of the 'Required Field' validators have been changed to the resource 'IdealForegroundColor'
