### ISSUE TITLE
Second time log of same timer type resets original

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#58]
If you add a timer of the same type as an existing timer log, the original timer log is reset to zero hours on today's date and the details are lost. Note that this will also reset timer logs of this type on previous days - they will also be set to zero time with no detail, and set to today's date.

**Comment by chri55w** [comment]
Issue caused by editing the Time Logs then refreshing prior to them saving, Modified the Refresh function to first check for Time Logs requiring updates.
