### ISSUE TITLE
Database import tool - managing hidden items

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#76]
All items - service items and classes - marked as Inactive in the database are automatically hidden in QuickBooks and in the timer application. When using the import tool to mark extra classes/items, still active but irrelevant to the timer application (e.g. VAT classes), all of the Inactive items are also shown in the left-hand column. They can be added to the hidden list or left there, and regardless of what goes on here will not be shown in the timer application, but it's confusing. They should either not show up in either column on this view or by default should be shown in the right-hand column of hidden items (and  it should not be possible to unhide them, if this is the chosen implementation).

**Comment by chri55w** [comment]
As discussed - my fault for missing half of an update! Columns are displayed in all tabs / DataGrids now from Update 2016-04-26 [2] for the Import Tool
