### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by AlexSoldevila** [chri55w/QuickBooks-Timer#81]
Just tried to start the application and got the attached crash. I haven't logged any time yet and just created two templates in my first session. If you need any files feel free to ask.
<img width="639" alt="crash" src="https://cloud.githubusercontent.com/assets/19147557/14952635/405f4f34-1062-11e6-8e57-43e9840e0227.PNG">

**Comment by chri55w** [comment]
That's a new one! thanks Alex, I'll take a look into that, i wonder did you notice if you had been disconnected from the Central Database at all in your last session?

**Comment by AlexSoldevila** [comment]
I didn't notice anything unusual in my previous session, although I may have missed it. I was able to create two templates and they became available under "My Templates" panel without apparent issues. Other than that I just closed the application without any other action.

**Comment by chri55w** [comment]
This is an issue involving the Database synchronization, this has now been re-explained in #85, development has been completed and changes are currently in the testing phase
