### ISSUE TITLE
Customer list sorting

### ISSUE THREAD

**Issue by spegler** [chri55w/QuickBooks-Timer#82]
Would be nice if the customer list was sorted when creating a new template.

**Comment by chri55w** [comment]
Applied sorting to all items in ComboBoxes throughout the New Template Flyout and the Edit Time Log Flyout
![image](https://cloud.githubusercontent.com/assets/10941226/15048953/acad1a58-12e3-11e6-9f52-9f0a3bf0bfb7.png)
