### ISSUE TITLE
Close fly-ins when action complete

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#89]
For example, when you create new timer log entry from a timer template, close the template fly-in and move focus to the timer log entry. Or when selecting "Log an Issue" from the Settings fly-in, close the fly-in :-)

**Comment by chri55w** [comment]
Perhaps best to have this as an option in the settings too? defaulted to close on an action

**Comment by BradConnor** [comment]
Could do, yes. Would also be good to look at things like: create a new timer from a template not only closes the fly-in, it sets focus to the new time AND if I have the time log edit fly-in marked as ‘pinned’, zoom that up – because, the first thing I want to do when I’ve created a new timer log entry is to key in some details about what I’m doing :)

**Comment by chri55w** [comment]
When enabled the new setting 'New Time Log Opens Edit Panel' opens the Edit flyout when a new time log is created. Clicking the 'Log an Issue or Suggestion' link closes the settings flyout and creating a new time log will also close the templates flyout
